// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
     
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGBRWSmA3T3ORw4vE1GJmJa4NesDCpqjU',
    appId: '1:449229581545:web:c12a4f5b6d947a37ffd478',
    messagingSenderId: '449229581545',
    projectId: 'chat-app-636a1',
    authDomain: 'chat-app-636a1.firebaseapp.com',
    storageBucket: 'chat-app-636a1.appspot.com',
    measurementId: 'G-KX1RN06SQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_DMaZ2B-_Rbndt85rfF4ckKQ5CXjAlyk',
    appId: '1:449229581545:android:23c68efad7968dc0ffd478',
    messagingSenderId: '449229581545',
    projectId: 'chat-app-636a1',
    storageBucket: 'chat-app-636a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf6lES1a2QPSX1WAZL5Jg5hsZpNGfP1ZM',
    appId: '1:449229581545:ios:1afcff8f5b509833ffd478',
    messagingSenderId: '449229581545',
    projectId: 'chat-app-636a1',
    storageBucket: 'chat-app-636a1.appspot.com',
    iosClientId:
        '449229581545-kmdb8q05ko9crie63db9q3objei1bqu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
